---
name: "tagged-release"

on:
  push:
    tags:
      - "*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: .

    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: make release

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: consul-timeline
